#!/bin/sh
set -e

apt-get update
apt-get upgrade -y
cd /opt/ruby-build
git pull
./install.sh

RUBY_230=2.3.0 # latest
RUBY_187=1.8.7-p375 # depreciated

RUBY230_PATH=/opt/rubies/2.3
RUBY187_PATH=/opt/rubies/1.8.7

export RUBY_CONFIGURE_OPTS="--disable-install-doc"
echo "gem: --no-ri --no-rdoc" > /.gemrc

export MAKE_OPTS="-j2"

mkdir -p /opt/passenger

echo "Installing $RUBY_230"
/usr/local/bin/ruby-build $RUBY_230 $RUBY230_PATH
PATH=$RUBY230_PATH/bin gem install bundler

echo "Installing $RUBY_187"
/usr/local/bin/ruby-build $RUBY_187 $RUBY187_PATH
PATH=$RUBY187_PATH/bin gem update --system 1.8.30
PATH=$RUBY187_PATH/bin gem install bundler rake

ln -s $RUBY230_PATH/bin/ruby /opt/passenger/ruby
