#!/bin/sh
set -e

apt-get update
apt-get upgrade -y

NGINX_VERSION=1.8.1
PASSENGER_VERSION=5.0.25

RUBY_230=2.3.0 # latest
RUBY_187=1.8.7-p374 # depreciated

RUBY230_PATH=/opt/rubies/2.3
RUBY187_PATH=/opt/rubies/1.8.7


TMP_PATH=/tmp/nginx-build

PATH_ORIG=$PATH
export PATH=$RUBY230_PATH/bin:$PATH_ORIG

mkdir -p $TMP_PATH
cd $TMP_PATH

# Fetch and extract Nginx
wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
tar xfz nginx-$NGINX_VERSION.tar.gz
cd nginx-$NGINX_VERSION

gem install passenger -v "$PASSENGER_VERSION"
ln -s $RUBY230_PATH/lib/ruby/gems/2.3.0/gems/passenger-$PASSENGER_VERSION /opt/passenger/root

# Configure passenger (with ubuntu-style paths)
passenger-install-nginx-module \
  --auto \
  --nginx-source-dir=$TMP_PATH/nginx-$NGINX_VERSION \
  --prefix=/usr \
  --extra-configure-flags=" \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/var/run/nginx.pid \
    --sbin-path=/usr/sbin \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --with-http_realip_module"

# Precompile passenger native_support for other rubies
# https://code.google.com/p/phusion-passenger/issues/detail?id=865
/opt/passenger/root/bin/passenger-config build-native-support

export PATH=$RUBY187_PATH/bin:$PATH_ORIG
/opt/passenger/root/bin/passenger-config build-native-support

cd /
rm -rf $TMP_PATH

echo "daemon off;" >> /etc/nginx/nginx.conf
