FROM ubuntu:precise

MAINTAINER Justin Geibel "jtgeibel@gmail.com"

RUN echo "deb http://security.ubuntu.com/ubuntu precise-security main" >> /etc/apt/sources.list && apt-get update && apt-get upgrade -y && apt-get clean # 2014-01-07