#!/bin/sh
set -e

export RUBY_CONFIGURE_OPTS="--disable-install-doc"
echo "gem: --no-ri --no-rdoc" > /root/.gemrc

mkdir -p /opt/rubies

echo "Installing 2.0.0"
/usr/local/bin/ruby-build 2.0.0-p247 /opt/rubies/2.0.0-p247

echo "Installing 1.9.3"
/usr/local/bin/ruby-build 1.9.3-p448 /opt/rubies/1.9.3-p448

echo "Installing 1.8.7"
/usr/local/bin/ruby-build 1.8.7-p374 /opt/rubies/1.8.7-p374