#!/bin/sh
set -e

NGINX_VERSION=1.4.4
RUBY_210=2.1.0
RUBY_200=2.0.0-p353
RUBY_193=1.9.3-p484
RUBY_187=1.8.7-p374

RUBY210_PATH=/opt/rubies/$RUBY_210/bin
RUBY200_PATH=/opt/rubies/$RUBY_200/bin
RUBY193_PATH=/opt/rubies/$RUBY_193/bin
RUBY187_PATH=/opt/rubies/$RUBY_187/bin
TMP_PATH=/tmp/nginx-build

PATH_ORIG=$PATH
export PATH=$RUBY210_PATH:$PATH_ORIG

mkdir -p $TMP_PATH
cd $TMP_PATH

# Fetch and extract Nginx
wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
tar xfz nginx-$NGINX_VERSION.tar.gz
cd nginx-$NGINX_VERSION

gem install passenger

# Configure passenger (with ubuntu-style paths)
passenger-install-nginx-module \
  --auto \
  --nginx-source-dir=$TMP_PATH/nginx-$NGINX_VERSION \
  --prefix=/usr \
  --extra-configure-flags=" \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/var/run/nginx.pid \
    --sbin-path=/usr/sbin \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --with-http_realip_module"

# Precompile passenger native_support for other rubies
# https://code.google.com/p/phusion-passenger/issues/detail?id=865
cd `passenger-config --root`
rake native_support

export PATH=$RUBY_200_PATH:$PATH_ORIG
rake native_support

export PATH=$RUBY193_PATH:$PATH_ORIG
rake native_support

export PATH=$RUBY187_PATH:$PATH_ORIG
rake native_support

cd /
rm -rf $TMP_PATH

echo "daemon off;" >> /etc/nginx/nginx.conf